import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/HomePage.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coders Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero Section */}
      <section className={styles.hero}>
        <div className={styles.container}>
          <h2 className={styles.heroTitle}>Code Better, Learn Faster</h2>
          <p className={styles.heroDescription}>
            Explore tutorials, coding challenges, and industry insights for developers.
          </p>
          <Link href='/blog'><button className={styles.ctaButton}>Get Started</button></Link>
        </div>
      </section>

      {/* Featured Blog Posts */}
      <section className={styles.featuredBlogs}>
        <h3 className={styles.sectionTitle}>Latest Blogs</h3>
        <div className={styles.blogGrid}>
          <div className={styles.blogCard}>
            <h4 className={styles.blogTitle}>Understanding React Hooks</h4>
            <p className={styles.blogDescription}>
              Learn how to use React Hooks in functional components to manage state and side effects.
            </p>
            <Link href='/blog'><button className={styles.ctaButton}>Read More</button></Link>
          </div>
          <div className={styles.blogCard}>
            <h4 className={styles.blogTitle}>JavaScript ES6 Features</h4>
            <p className={styles.blogDescription}>
              Discover the most useful ES6 features that make your JavaScript code more efficient and clean.
            </p>
            <Link href='/blog'><button className={styles.ctaButton}>Read More</button></Link>
          </div>
          <div className={styles.blogCard}>
            <h4 className={styles.blogTitle}>CSS Grid Layout Guide</h4>
            <p className={styles.blogDescription}>
              A comprehensive guide to mastering CSS Grid Layout with practical examples.
            </p>
            <Link href='/blog'><button className={styles.ctaButton}>Read More</button></Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className={styles.footer}>
        <p>&copy; 2024 Coders Blog. All rights reserved.</p>
      </footer>
    </div>
  )
}
