import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coders Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx>{`
      .background {
        width : 300px;
      }
      `}
      </style>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Coders Blog
        </h1>

        <p className={styles.description}>
          A blog for coders by Codes Blog
        </p>
        <div className='background'>
        <Image src="/background.jpg"  width={1000} height={677} layout="intrinsic"/>
        </div>
        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn Javascript in 2024</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. </p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2024</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. </p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2024</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
